"""Unit tests for the YouTube Publishing Provider boundary."""

from datetime import UTC, datetime
from io import BytesIO
from typing import Literal
from unittest.mock import Mock
from uuid import uuid4

import pytest
from pydantic import SecretStr

from apps.api.assets.models import Asset
from apps.api.publishing.youtube import (
    YouTubeAssetRetrievalError,
    YouTubeConfigurationError,
    YouTubeCredentialSettings,
    YouTubeInvalidMediaError,
    YouTubeMalformedResponseError,
    YouTubePublishingProvider,
    YouTubeUploadError,
)
from apps.api.storage import ObjectStorage, StorageOperationError, StoredObject


def video_asset() -> Asset:
    return Asset(
        id=uuid4(),
        object_key="assets/runtime/final.mp4",
        filename="final.mp4",
        content_type="video/mp4",
        size_bytes=5,
        created_at=datetime.now(UTC),
    )


def credentials(*, configured: bool = True) -> YouTubeCredentialSettings:
    suffix = "fixture" if configured else ""
    return YouTubeCredentialSettings(
        client_id=SecretStr(suffix),
        client_secret=SecretStr(suffix),
        refresh_token=SecretStr(suffix),
    )


def storage_returning(
    body: bytes = b"video",
    content_type: str = "video/mp4",
) -> Mock:
    storage = Mock(spec=ObjectStorage)
    storage.download = Mock()

    async def download(key: str) -> StoredObject:
        assert key == "assets/runtime/final.mp4"
        return StoredObject(body=body, content_type=content_type)

    storage.download.side_effect = download
    return storage


class FakeRequest:
    def __init__(self, response: object = None, error: Exception | None = None) -> None:
        self.response = response
        self.error = error

    def execute(self) -> object:
        if self.error is not None:
            raise self.error
        return self.response


class FakeVideos:
    def __init__(self, request: FakeRequest) -> None:
        self.request = request
        self.insert_kwargs: dict[str, object] = {}

    def insert(self, **kwargs: object) -> FakeRequest:
        self.insert_kwargs = kwargs
        return self.request


class FakeYouTubeClient:
    def __init__(self, videos: FakeVideos) -> None:
        self._videos = videos

    def videos(self) -> FakeVideos:
        return self._videos


def provider_with_response(
    response: object,
    *,
    privacy_status: Literal["private", "unlisted", "public"] = "private",
    storage: Mock | None = None,
    error: Exception | None = None,
) -> tuple[YouTubePublishingProvider, FakeVideos, list[BytesIO]]:
    videos = FakeVideos(FakeRequest(response=response, error=error))
    streams: list[BytesIO] = []

    def media_factory(stream: BytesIO, content_type: str) -> object:
        assert content_type == "video/mp4"
        assert stream.read() == b"video"
        stream.seek(0)
        streams.append(stream)
        return "media-upload"

    provider = YouTubePublishingProvider(
        storage or storage_returning(),
        credentials(),
        privacy_status=privacy_status,
        client_factory=lambda: FakeYouTubeClient(videos),
        media_upload_factory=media_factory,
    )
    return provider, videos, streams


@pytest.mark.asyncio
async def test_upload_maps_metadata_private_default_and_normalizes_response() -> None:
    provider, videos, streams = provider_with_response({"id": "AbC_123-xY"})

    response = await provider.publish(
        video_asset(),
        title="Launch video",
        description="Generated by AI Video OS",
    )

    assert videos.insert_kwargs["part"] == "snippet,status"
    assert videos.insert_kwargs["body"] == {
        "snippet": {
            "title": "Launch video",
            "description": "Generated by AI Video OS",
        },
        "status": {"privacyStatus": "private"},
    }
    assert videos.insert_kwargs["media_body"] == "media-upload"
    assert videos.insert_kwargs["notifySubscribers"] is False
    assert response.external_id == "AbC_123-xY"
    assert response.external_url == "https://www.youtube.com/watch?v=AbC_123-xY"
    assert response.metadata == {"provider": "youtube", "privacy_status": "private"}
    assert streams[0].closed


@pytest.mark.asyncio
async def test_explicit_unlisted_privacy_and_empty_description() -> None:
    provider, videos, _ = provider_with_response({"id": "video-id"}, privacy_status="unlisted")

    response = await provider.publish(video_asset(), title="Title", description=None)

    assert videos.insert_kwargs["body"] == {
        "snippet": {"title": "Title", "description": ""},
        "status": {"privacyStatus": "unlisted"},
    }
    assert response.metadata["privacy_status"] == "unlisted"


@pytest.mark.asyncio
async def test_missing_credentials_fails_before_storage_or_client_use() -> None:
    storage = storage_returning()
    client_factory = Mock()
    provider = YouTubePublishingProvider(
        storage,
        credentials(configured=False),
        client_factory=client_factory,
    )

    with pytest.raises(YouTubeConfigurationError) as raised:
        await provider.publish(video_asset(), title="Title", description=None)

    assert raised.value.code == "YOUTUBE_CONFIGURATION_ERROR"
    storage.download.assert_not_called()
    client_factory.assert_not_called()


@pytest.mark.asyncio
async def test_storage_and_invalid_media_errors_are_normalized() -> None:
    failing_storage = storage_returning()
    failing_storage.download.side_effect = StorageOperationError()
    provider = YouTubePublishingProvider(failing_storage, credentials())

    with pytest.raises(YouTubeAssetRetrievalError):
        await provider.publish(video_asset(), title="Title", description=None)

    provider, _, _ = provider_with_response(
        {"id": "video-id"}, storage=storage_returning(content_type="image/png")
    )
    with pytest.raises(YouTubeInvalidMediaError):
        await provider.publish(video_asset(), title="Title", description=None)


@pytest.mark.asyncio
@pytest.mark.parametrize("response", [{}, {"id": ""}, {"id": "invalid id"}, None])
async def test_malformed_responses_are_rejected(response: object) -> None:
    provider, _, _ = provider_with_response(response)

    with pytest.raises(YouTubeMalformedResponseError):
        await provider.publish(video_asset(), title="Title", description=None)


@pytest.mark.asyncio
async def test_sdk_exception_is_normalized_without_exposing_details() -> None:
    provider, _, _ = provider_with_response(
        None,
        error=RuntimeError("sensitive sdk response"),
    )

    with pytest.raises(YouTubeUploadError) as raised:
        await provider.publish(video_asset(), title="Title", description=None)

    assert raised.value.code == "YOUTUBE_UPLOAD_ERROR"
    assert "sensitive" not in raised.value.safe_message
